### Obtener todas las marcas
GET http://localhost:3000/api/marcas

### Crear una marca (creado)
# @name createMarca
POST http://localhost:3000/api/marcas
Content-Type: application/json

{
    "nombre": "Renault"
}

### ID
@id = {{createMarca.response.body.data.id}}
# esto no se bien q es despues lo arreglo

### Obtener una Marca
GET http://localhost:3000/api/marcas/{{id}}

### PUT => Modificaciones completas (Recurso completo e idempotente)
### PATCH => Modificaciones parciales o completas

### Modificar una marca (PUT)
PUT http://localhost:3000/api/marcas/{{id}}
Content-Type: application/json

{
  "nombre": "Fiat",
}

### Modificar una marca (PATCH)
PATCH  http://localhost:3000/api/marcas/{{id}}
Content-Type: application/json

{
  "nombre": "Toyota"
}

### Crear una marca para eliminar
# @name createMarcaToDelete
POST http://localhost:3000/api/marcas
Content-Type: application/json

{
    "nombre": "Fiat",
}

### Eliminar una marca
@idToDelete = {{createMarcaToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/marcas/{{idToDelete}}

### Crear una marca (creado)
POST http://localhost:3000/api/marcas
Content-Type: application/json

{
    "nombre": "Ford"
}

### Crear una marca (creado)
POST http://localhost:3000/api/marcas
Content-Type: application/json

{
    "nombre": "Audi"
}