### POST 1
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "locationName": "Rosario Norte",
    "address": "Rondeau 1200",
    "phoneNumber": "3416259147"
}

### GET ONE
GET http://localhost:3000/api/locations/1

### PUT
PUT  http://localhost:3000/api/locations/1
Content-Type: application/json

{
    "locationName": "Rosario Norte",
    "address": "San Martin 5100",
    "phoneNumber": "3416259147"
}

### POST 2
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "locationName": "Rosario Oeste",
    "address": "Eva Peron 6400",
    "phoneNumber": "3413678231"
}

### POST 3 (to DELETE)
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "locationName": "Rosario Centro",
    "address": "Ovidio Lagos 900",
    "phoneNumber": "3417214794"
}

### GET ALL
GET http://localhost:3000/api/locations

### DELETE
DELETE http://localhost:3000/api/locations/3