import { Routes } from '@angular/router';
import { HomePageComponent } from './home-page/home-page.component';
import { ClientsComponent } from './cli-folder/clients/clients.component';
import { ClientFormComponent } from './cli-folder/client-form/client-form.component';
import { CategoriasComponent } from './cat-folder/categorias/categorias.component';
import { CategoriaFormComponent } from './cat-folder/categoria-form/categoria-form.component';
import { MarcasComponent } from './mar-folder/marcas/marcas.component';
import { MarcaFormComponent } from './mar-folder/marca-form/marca-form.component';
import { ColorsComponent } from './col-folder/colors/colors.component';
import { ColorFormComponent } from './col-folder/color-form/color-form.component';
import { SucursalesComponent } from './suc-folder/sucursales/sucursales.component';
import { SucursalFormComponent } from './suc-folder/sucursal-form/sucursal-form.component';
import { ModelosComponent } from './mod-folder/modelos/modelos.component';
import { ModeloFormComponent } from './mod-folder/modelo-form/modelo-form.component';
import { VehicleListComponent } from './vehicle-list/vehicle-list.component';
import { TestMatiComponent } from './test/test-mati/test-mati.component.js';

export const routes: Routes = [
  { path: 'home', component: HomePageComponent },
  { path: 'clientes', component: ClientsComponent },
  { path: 'clientes/creacion', component: ClientFormComponent },
  { path: 'clientes/modificacion/:id', component: ClientFormComponent },
  { path: 'categorias', component: CategoriasComponent },
  { path: 'categorias/creacion', component: CategoriaFormComponent },
  { path: 'categorias/modificacion/:id', component: CategoriaFormComponent },
  { path: 'marcas', component: MarcasComponent },
  { path: 'marcas/creacion', component: MarcaFormComponent },
  { path: 'marcas/modificacion/:id', component: MarcaFormComponent },
  { path: 'colores', component: ColorsComponent },
  { path: 'colores/creacion', component: ColorFormComponent },
  { path: 'colores/modificacion/:id', component: ColorFormComponent },
  { path: 'sucursales', component: SucursalesComponent },
  { path: 'sucursales/creacion', component: SucursalFormComponent },
  { path: 'sucursales/modificacion/:id', component: SucursalFormComponent },
  { path: 'modelos', component: ModelosComponent },
  { path: 'modelos/creacion', component: ModeloFormComponent },
  { path: 'modelos/modificacion/:id', component: ModeloFormComponent },
  { path: 'vehiculos', component: VehicleListComponent },
  { path: 'testMati', component: TestMatiComponent },
  { path: '', redirectTo: 'home', pathMatch: 'full' },
];
