### GET ALL
http://localhost:3000/api/categorias


### POST
# @name createCategoria
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "SUV",
    "descripcion": "Vehículos robustos y espaciosos, ideales para familias o viajes de aventura.",
    "precioPorDia": 100,
    "valorDeposito": 500
}

### ID
@id = {{createCategoria.response.body.data.id}}

### GET ONE
http://localhost:3000/api/categorias/{{id}}

### PUT
PUT http://localhost:3000/api/categorias/{{id}}
Content-Type: application/json

{
    "nombre": "SUV",
    "descripcion": "Vehículos robustos y espaciosos, ideales para familias o viajes de aventura.",
    "precioPorDia": 150,
    "valorDeposito": 570
}

### POST 2
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "Camioneta",
    "descripcion": "Vehículos grandes y robustos, ideales para transportar cargas o remolcar vehículos.",
    "precioPorDia": 150,
    "valorDeposito": 750
}

### POST to DELETE
# @name createCategoriaToDelete
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "Deportivo",
    "descripcion": "Vehículos que destacan por su rendimiento y diseño deportivo.",
    "precioPorDia": 120,
    "valorDeposito": 600
}

### DELETE
@idToDelete = {{createCategoriaToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/categorias/{{idToDelete}}

