### POST 1
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "OAS135",
    "manufacturingYear": "2010",
    "totalKms": 2500,
    "location": 1,
    "color": 2,
    "vehicleModel": 1
}

### GET ONE
GET http://localhost:3000/api/vehicles/1


### PUT
PUT http://localhost:3000/api/vehicles/1
Content-Type: application/json

{
    "licensePlate": "OAS135",
    "manufacturingYear": "2010",
    "totalKms": 3000,
    "location": 1,
    "color": 2,
    "vehicleModel": 1
}

### POST 2
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "COT872",
    "manufacturingYear": "2000",
    "totalKms": 13000,
    "location": 3,
    "color": 1,
    "vehicleModel": 3
}

### POST 3 (to DELETE)
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "TGB461",
    "manufacturingYear": "2020",
    "totalKms": 1500,
    "location": 2,
    "color": 2,
    "vehicleModel": 3
}

### GET ALL
http://localhost:3000/api/vehicles


### FIND AVAILABLE
GET http://localhost:3000/api/vehicles/available?startDate=2025-01-15&endDate=2025-01-25&location=1

### DELETE
DELETE http://localhost:3000/api/vehicles/3