### POST 1
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "categoryName": "SUV",
    "categoryDescription": "Vehículos robustos y espaciosos, ideales para familias o viajes de aventura.",
    "pricePerDay": 100,
    "depositValue": 60
}

### GET ONE
http://localhost:3000/api/categories/1

### PUT
PUT http://localhost:3000/api/categories/1
Content-Type: application/json

{
    "categoryName": "SUV",
    "categoryDescription": "Vehículos robustos y espaciosos, ideales para familias o viajes de aventura.",
    "pricePerDay": 150,
    "depositValue": 60
}

### POST 2
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "categoryName": "Camioneta",
    "categoryDescription": "Vehículos grandes y robustos, ideales para transportar cargas o remolcar vehículos.",
    "pricePerDay": 200,
    "depositValue": 120
}

### POST 3 (to DELETE)
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "categoryName": "Deportivo",
    "categoryDescription": "Vehículos que destacan por su rendimiento y diseño deportivo.",
    "pricePerDay": 250,
    "depositValue": 180
}

### GET ALL
http://localhost:3000/api/categories

### DELETE
DELETE http://localhost:3000/api/categories/3