### POST 1
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
    "reservationDate": "2025-01-01",
    "startDate": "2025-02-16",
    "plannedEndDate": "2025-02-20",
    "user": 1,
    "vehicle": 1
}

### GET ONE
http://localhost:3000/api/reservations/1

### POST 2
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
    "reservationDate": "2025-01-05",
    "startDate": "2025-01-22",
    "plannedEndDate": "2025-01-29",
    "user": 2,
    "vehicle": 1
}

### POST 3 (to DELETE)
POST http://localhost:3000/api/reservations
Content-Type: application/json

{
    "reservationDate": "2025-01-06",
    "startDate": "2025-01-24",
    "plannedEndDate": "2025-01-31",
    "user": 3,
    "vehicle": 2
}

### GET ALL
http://localhost:3000/api/reservations

### DELETE
DELETE http://localhost:3000/api/reservations/3