### Obtener todos los clientes
GET http://localhost:8000/api/clientes

### Obtener un cliente
GET http://localhost:8000/api/clientes/06fcac53-6f08-4516-906b-cdf1949ac01d

### Crear un cliente
POST http://localhost:8000/api/clientes
Content-Type: application/json

{
    "tipoDoc": "DNI",
    "nroDoc": "34346437",
    "nombre": "Marcos",
    "apellido": "Godoy",
    "fechaNacimiento": "27/05/2007",
    "mail": "mjgodo@gmail.com",
    "domicilio": "Pellegrini 1302",
    "telefonos": ["4345648","3415642126"],
    "nacionalidad": "Paraguayo"
}

### Modificar un cliente
### PUT => Modificaciones completas (Recurso completo e idempotente)
### PATCH => Modificaciones parciales o completas
PUT http://localhost:8000/api/clientes/06fcac53-6f08-4516-906b-cdf1949ac01d
Content-Type: application/json

{
      "tipoDoc": "DNI",
      "nroDoc": "44213356",
      "nombre": "Matias",
      "apellido": "Marquez",
      "fechaNacimiento": "26/02/2024",
      "mail": "matiasmarquesito@gmail.com",
      "domicilio": "Machuchi 2145",
      "telefonos": [
        "2453243",
        "1252993525"
      ],
      "nacionalidad": "Argentino"
}