### POST 1
POST http://localhost:3000/api/colors
Content-Type: application/json

{
    "colorName": "Azul"
}

### GET ONE
GET http://localhost:3000/api/colors/1


### PUT
PUT  http://localhost:3000/api/colors/1
Content-Type: application/json

{
    "colorName": "Rojo"
}

### POST 2
POST http://localhost:3000/api/colors
Content-Type: application/json

{
    "colorName": "Amarillo"
}

### POST 3 (to DELETE)
POST http://localhost:3000/api/colors
Content-Type: application/json

{
    "colorName": "Negro"
}

### GET ALL
GET http://localhost:3000/api/colors

### DELETE
DELETE http://localhost:3000/api/colors/3