### GET ALL
GET http://localhost:3000/api/locations

### POST
# @name createLocation
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "locationName": "Rosario Norte",
    "address": "Rondeau 1200",
    "phoneNumber": "3416259147"
}

### ID
@id = {{createLocation.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/locations/123123


### PUT
PUT  http://localhost:3000/api/locations/1
Content-Type: application/json

{
    "locationName": "Rosario Norte",
    "address": "San Martin 5100",
    "phoneNumber": "3415367981"
}

### POST 2
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "locationName": "Rosario Oeste",
    "address": "Eva Peron 6400",
    "phoneNumber": "3413678231"
}

### POST 3
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "locationName": "Rosario Centro",
    "address": "Ovidio Lagos 900",
    "phoneNumber": "3417214794"
}

### POST to DELETE
# @name createLocationToDelete
POST http://localhost:3000/api/locations
Content-Type: application/json

{
    "locationName": "Funes",
    "address": "Fuerza Aerea 3500",
    "phoneNumber": "3416732893"
}

### DELETE
@idToDelete = {{createLocationToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/locations/12