### GET ALL
http://localhost:3000/api/vehicles


### POST
# @name createVehicle
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "OAS135",
    "manufacturingYear": "2010",
    "totalKms": "2500",
    "location": 1,
    "color": 2,
    "vehicleModel": 1
}

### ID
@id = {{createVehicle.response.body.data.id}}

### GET ONE
http://localhost:3000/api/vehicles/{{id}}

### PUT
PUT http://localhost:3000/api/vehicles/{{id}}
Content-Type: application/json

{
    "licensePlate": "POP135",
    "manufacturingYear": "2014",
    "totalKms": "2500",
    "location": 1,
    "color": 2,
    "vehicleModel": 1
}

### POST 2
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "COC567",
    "manufacturingYear": "2000",
    "totalKms": 13000,
    "location": 3,
    "color": 1,
    "vehicleModel": 3
}

### POST 3
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "AAA333",
    "manufacturingYear": "2020",
    "totalKms": 10,
    "location": 2,
    "color": 2,
    "vehicleModel": 3
}

### POST to DELETE
# @name createVehicleToDelete
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "RTY123",
    "manufacturingYear": "2003",
    "totalKms": 8600,
    "location": 5,
    "color": 3,
    "vehicleModel": 2
}

### POST to DELETE
# @name createVehicleToDelete
POST http://localhost:3000/api/vehicles
Content-Type: application/json

{
    "licensePlate": "RTT111",
    "manufacturingYear": "2000",
    "totalKms": 200,
    "location": 2,
    "color": 2,
    "vehicleModel": 2
}

### DELETE
@idToDelete = {{createVehicleToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/vehicles/{{idToDelete}}
