### POST 1
POST http://localhost:3000/api/vehicle-models
Content-Type: application/json

{
    "vehicleModelName": "Corolla",
    "transmissionType": "Automatica",
    "passengerCount": 5,
    "imagePath": "assets/img/Corolla.jpg",
    "category": 1,
    "brand": 1
}

### GET ONE
GET http://localhost:3000/api/vehicle-models/1

### PUT
PUT  http://localhost:3000/api/vehicle-models/1
Content-Type: application/json

{
    "vehicleModelName": "Corolla",
    "transmissionType": "Automatica",
    "passengerCount": 6,
    "imagePath": "assets/img/corolla.jpg",
    "category": 1,
    "brand": 1
}

### POST 2
POST http://localhost:3000/api/vehicle-models
Content-Type: application/json

{
    "vehicleModelName": "Civic",
    "transmissionType": "Manual",
    "passengerCount": 4,
    "imagePath": "assets/img/Civic.jpg",
    "category": 1,
    "brand": 2
}

### POST 3 (to DELETE)
POST http://localhost:3000/api/vehicle-models
Content-Type: application/json

{
    "vehicleModelName": "F-150",
    "transmissionType": "Automatica",
    "passengerCount": 6,
    "imagePath": "assets/img/f150.jpg",
    "category": 2,
    "brand": 3
}

### GET ALL
GET http://localhost:3000/api/vehicle-models

### DELETE
DELETE http://localhost:3000/api/vehicle-models/3