### GET ALL
GET http://localhost:3000/api/colors

### POST
# @name createColor
POST http://localhost:3000/api/colors
Content-Type: application/json

{
    "colorName": "Azul"
}

### ID
@id = {{createColor.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/colors/{{id}}


### PUT
PUT  http://localhost:3000/api/colors/{{id}}
Content-Type: application/json

{
    "colorName": "Rojo"
}

### POST 2
POST http://localhost:3000/api/colors
Content-Type: application/json

{
    "colorName": "Amarillo"
}

### POST 3
POST http://localhost:3000/api/colors
Content-Type: application/json

{
    "colorName": "Negro"
}

### POST to DELETE
# @name createColorToDelete
POST http://localhost:3000/api/colors
Content-Type: application/json

{
    "colorName": "Blanco"
}

### DELETE
@idToDelete = {{createColorToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/colors/{{idToDelete}}

### DELETE
DELETE http://localhost:3000/api/upload/gol.jfif