### GET ALL
http://localhost:3000/api/vehiculos


### POST
# @name createVehiculo
POST http://localhost:3000/api/vehiculos
Content-Type: application/json

{
    "patente": "OAS135",
    "anioFabricacion": "2010",
    "kmRecorridos": "2500",
    "sucursal": 1,
    "color": 2,
    "modelo": 1
}

### ID
@id = {{createVehiculo.response.body.data.id}}

### GET ONE
http://localhost:3000/api/vehiculos/{{id}}

### PUT
PUT http://localhost:3000/api/vehiculos/{{id}}
Content-Type: application/json

{
    "patente": "POP135",
    "anioFabricacion": "2014",
    "kmRecorridos": "2500",
    "sucursal": 1,
    "color": 2,
    "modelo": 1
}

### POST 2
POST http://localhost:3000/api/vehiculos
Content-Type: application/json

{
    "patente": "COC567",
    "anioFabricacion": "2000",
    "kmRecorridos": 13000,
    "sucursal": 3,
    "color": 1,
    "modelo": 3
}

### POST 3
POST http://localhost:3000/api/vehiculos
Content-Type: application/json

{
    "patente": "AAA333",
    "anioFabricacion": "2020",
    "kmRecorridos": 10,
    "sucursal": 2,
    "color": 2,
    "modelo": 3
}

### POST to DELETE
# @name createVehiculoToDelete
POST http://localhost:3000/api/vehiculos
Content-Type: application/json

{
    "patente": "RTY123",
    "anioFabricacion": "2003",
    "kmRecorridos": 8600,
    "sucursal": 5,
    "color": 3,
    "modelo": 2
}

### POST to DELETE
# @name createVehiculoToDelete
POST http://localhost:3000/api/vehiculos
Content-Type: application/json

{
    "patente": "RTT111",
    "anioFabricacion": "2000",
    "kmRecorridos": 200,
    "sucursal": 2,
    "color": 2,
    "modelo": 2
}

### DELETE
@idToDelete = {{createVehiculoToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/vehiculos/{{idToDelete}}
