### Obtener todos los modelos de vehiculos
GET http://localhost:3000/api/vehiculos/modelos

### Crear un modelo de vehiculo (creado)
# @name createModeloVehiculo
POST http://localhost:3000/api/vehiculos/modelos
Content-Type: application/json

{
    "nombre": "Audi A4",
    "tipoTransmision": "manual",
    "cantPasajeros": 5,
    // agrego una marca
    //"marca": 1232123
}

### ID
@id = {{createModeloVehiculo.response.body.data.id}}

### Obtener un modelo de vehiculo
GET http://localhost:3000/api/vehiculos/modelos/{{id}}


### Modificar un modelo de vehiculo
PUT  http://localhost:3000/api/vehiculos/modelos/{{id}}
Content-Type: application/json

{
    "nombre": "Audi A4",
    "tipoTransmision": "automatico",
    "cantPasajeros": 30
}

### POST2 (creado)
POST http://localhost:3000/api/vehiculos/modelos
Content-Type: application/json

{
    "nombre": "BMW Serie 3",
    "tipoTransmision": "manual",
    "cantPasajeros": 10
}

### POST3 (creado)
POST http://localhost:3000/api/vehiculos/modelos
Content-Type: application/json

{
    "nombre": "Citroen C4",
    "tipoTransmision": "automatico",
    "cantPasajeros": 3
}

### Crear modelo de vehiculo apara eliminar
# @name createModeloVehiculoToDelete
POST http://localhost:3000/api/vehiculos/modelos
Content-Type: application/json

{
    "nombre": "Audi AAAAAAA4",
    "tipoTransmision": "manual",
    "cantPasajeros": 5
}

### Borrar un modelo de vehiculo
@idToDelete = {{createModeloVehiculoToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/vehiculos/modelos/{{idToDelete}}