### Obtener todos los alquileres
http://localhost:3000/api/alquileres


### Crear un alquiler (creado)
# @name createAlquiler
POST http://localhost:3000/api/alquileres
Content-Type: application/json

{
    "kmRecorridos": 23,
    "fechaAlquiler": "2021-06-20",
    "fechaFin": "2021-06-20",
    "tarifa": 2000,
    "vehiculo": "66957e785581ba773eccd161",
    "cliente": "66957f4b5581ba773eccd164"
}

### ID
@id = {{createAlquiler.response.body.data.id}}

### Obtener un alquiler
http://localhost:3000/api/alquileres/{{id}}

### Modificar un alquiler
PUT http://localhost:3000/api/alquileres/{{id}}
Content-Type: application/json

{
    "kmRecorridos": 1233,
    "fechaAlquiler": "2021-06-20",
    "fechaFin": "2021-06-20",
    "tarifa": 2044400,
    "vehiculo": "66957e785581ba773eccd161",
    "cliente": "66957f4b5581ba773eccd164"
}

### Crear un alquiler (creado)
POST http://localhost:3000/api/alquileres
Content-Type: application/json

{
    "kmRecorridos": 1000000,
    "fechaAlquiler": "2022-06-10",
    "fechaFin": "2022-07-10",
    "tarifa": 204440110,
    "vehiculo": "66957ebd5581ba773eccd162",
    "cliente": "66957fd75581ba773eccd166"
}

### Crear un alquiler para eliminar
# @name createAlquilerToDelete
POST http://localhost:3000/api/alquileres
Content-Type: application/json

{
    "kmRecorridos": 14445000000,
    "fechaAlquiler": "2024-06-10",
    "fechaFin": "2024-07-10",
    "tarifa": 2110,
    "vehiculo": "66957ec15581ba773eccd163",
    "cliente": "66957fd75581ba773eccd166"
}
### Eliminar alquiler creado
@idToDelete = {{createAlquilerToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/alquileres/{{idToDelete}}

