### Obtener todos los clientes
GET http://localhost:3000/api/clientes

### Obtener un cliente
GET http://localhost:3000/api/clientes/666753a0cccba6d092cdcdf7

### Crear un cliente (Ya creado)
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
    "tipoDoc": "DNI",
    "nroDoc": "12463545",
    "nombre": "Cristobal",
    "apellido": "Colón",
    "fechaNacimiento": "02/10/2024",
    "mail": "cristobalito@gmail.com",
    "domicilio": "Ayacucho 1023",
    "telefono": "12334122",
    "nacionalidad": "Tucumano"
}


### PUT => Modificaciones completas (Recurso completo e idempotente)
### PATCH => Modificaciones parciales o completas
### Modificar un cliente (PUT)
PUT http://localhost:3000/api/clientes/666753a0cccba6d092cdcdf7
Content-Type: application/json

{
  "tipoDoc": "DNI",
  "nroDoc": "44213356",
  "nombre": "Matias",
  "apellido": "Marquez",
  "fechaNacimiento": "26/02/2024",
  "mail": "matiasmarquesito@gmail.com",
  "domicilio": "Macuchi 2145",
  "telefono": "2453243",
  "nacionalidad": "Argentino"
}

### Modificar un cliente (PATCH)
PATCH  http://localhost:3000/api/clientes/666753a0cccba6d092cdcdf7
Content-Type: application/json

{
      "tipoDoc": "DNI",
      "nroDoc": "44213356",
      "fechaNacimiento": "26/02/2024",
      "mail": "matiasmaaaaaaaaaaarquesito@gmail.com",
      "domicilio": "Machuchi 2145",
      "telefonos": "1252993525"
}

### Borrar un cliente
DELETE http://localhost:3000/api/clientes/66675097871c807bfcac79b3
