### GET ALL
GET http://localhost:3000/api/clientes

### POST
# @name createCliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "tipoDoc": "DNI",
  "nroDoc": "34617640",
  "nombre": "Juan",
  "apellido": "Perez",
  "fechaNacimiento": "1980-01-01",
  "mail": "juan.perez@gmail.com",
  "domicilio": "Ayacucho 1023",
  "telefono": "3416893525",
  "nacionalidad": "Argentina"
}

### ID
@id = {{createCliente.response.body.data.id}}

### GET ONE
# @name createCliente
GET http://localhost:3000/api/clientes/{{id}}

### PUT
PUT http://localhost:3000/api/clientes/{{id}}
Content-Type: application/json

{
  "tipoDoc": "DNI",
  "nroDoc": "34617640",
  "nombre": "Juan",
  "apellido": "Perez",
  "fechaNacimiento": "1980-01-01",
  "mail": "juan.perez@hotmail.com",
  "domicilio": "Ayacucho 2431",
  "telefono": "3416893525",
  "nacionalidad": "Argentina"
}

### POST 2
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "tipoDoc": "Pasaporte",
  "nroDoc": "AB1234567",
  "nombre": "Peter",
  "apellido": "Griffin",
  "fechaNacimiento": "1975-03-28",
  "mail": "peter.griffin@yahoo.com",
  "domicilio": "24 Cottrill St.",
  "telefono": "3055551212",
  "nacionalidad": "Estados Unidos"
}

### POST 3
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "tipoDoc": "Pasaporte",
  "nroDoc": "BA45678932",
  "nombre": "Lionel",
  "apellido": "Messi",
  "fechaNacimiento": "1965-03-18",
  "mail": "d10s@gmail.com",
  "domicilio": "Miami 123",
  "telefono": "305555231",
  "nacionalidad": "Argentino"
}

### POST to DELETE
# @name createClienteToDelete
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "tipoDoc": "DNI",
  "nroDoc": "21375376",
  "nombre": "Ana",
  "apellido": "Garcia",
  "fechaNacimiento": "1990-02-15",
  "mail": "ana.garcia@hotmail.com",
  "domicilio": "Laprida 742",
  "telefono": "3413528690",
  "nacionalidad": "Argentina"
}

### DELETE
@idToDelete = {{createClienteToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/clientes/{{idToDelete}}
