### GET ALL
http://localhost:3000/api/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJlamVtcGxvQGdtYWlsLmNvbSIsImlhdCI6MTcyMzkxNjUzNywiZXhwIjoxNzIzOTIwMTM3fQ.D5jJUtImuJBpunfN9v_CejSNbzVoK0BBwY215BBxygY


### REGISTER
# @name createUsuario
POST http://localhost:3000/api/usuarios/register
Content-Type: application/json

{
    "email": "ejemplo2@gmail.com",
    "contraseña": "password"
}

### LOGIN
POST http://localhost:3000/api/usuarios/login
Content-Type: application/json

{
    "email": "ejemplo@gmail.com",
    "contraseña": "password"
}

### ID
@id = {{createUsuario.response.body.data.id}}

### GET ONE
http://localhost:3000/api/usuarios/{{id}}

### PUT
PUT http://localhost:3000/api/usuarios/{{id}}
Content-Type: application/json

{
    "email": "ejemploPUT@gmail.com",
    "contraseña": "password"
}

### POST 2
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "email": "ejemplo2@gmail.com",
    "contraseña": "password2"
}
### POST to DELETE
# @name createUsuarioToDelete
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "email": "ejemploDelete@gmail.com",
    "contraseña": "password3"
}

### DELETE
@idToDelete = {{createUsuarioToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/usuarios/{{idToDelete}}

