### GET ALL
GET http://localhost:3000/api/brands

### POST
# @name createBrand
POST http://localhost:3000/api/brands
Content-Type: application/json

{
  "brandName": "Toyotas"
}

### ID
@id = {{createBrand.response.body.data.id}}
# esto no se bien q es despues lo arreglo

### Obtener una Marca
GET http://localhost:3000/api/brands/1

### PUT => Modificaciones completas (Recurso completo e idempotente)
### PATCH => Modificaciones parciales o completas

### Modificar una marca (PUT)
PUT http://localhost:3000/api/brands/1422
Content-Type: application/json

{
  "brandName": "Fifas"
}

### POST 2
POST http://localhost:3000/api/brands
Content-Type: application/json

{
  "brandName": "Honda"
}

### POST 3
POST http://localhost:3000/api/brands
Content-Type: application/json

{
  "brandName": "Ford"
}

### POST to DELETE
# @name createBrandToDelete
POST http://localhost:3000/api/brands
Content-Type: application/json

{
  "brandName": "Chevrolet"
}

### DELETE
@idToDelete = {{createBrandToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/brands/1